import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import jsPDF from 'jspdf';

export async function createSamplePdf(title: string, textLines: string[]): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595.28, 841.89]); // A4
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const { height } = page.getSize();

  // Header banner
  page.drawRectangle({
    x: 40,
    y: height - 80,
    width: 515.28,
    height: 40,
    color: rgb(0.14, 0.38, 0.92),
  });

  page.drawText(title, {
    x: 55,
    y: height - 65,
    size: 16,
    font: boldFont,
    color: rgb(1, 1, 1),
  });

  let currentY = height - 120;
  for (const line of textLines) {
    if (currentY < 60) break;
    const isHeading = line.startsWith('#') || (line.toUpperCase() === line && line.length < 40);
    page.drawText(line.replace(/^#+\s*/, '').slice(0, 80), {
      x: 50,
      y: currentY,
      size: isHeading ? 12 : 10,
      font: isHeading ? boldFont : font,
      color: isHeading ? rgb(0.1, 0.15, 0.25) : rgb(0.2, 0.25, 0.3),
    });
    currentY -= isHeading ? 22 : 16;
  }

  // Footer
  page.drawText('Generated by PDFMind AI — Document Intelligence Workspace', {
    x: 50,
    y: 30,
    size: 8,
    font,
    color: rgb(0.6, 0.65, 0.7),
  });

  return await pdfDoc.save();
}

export async function createSamplePdfFile(title: string, content: string): Promise<Uint8Array> {
  const lines = content.split('\n').filter(Boolean);
  return await createSamplePdf(title, lines);
}

export function downloadBlob(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadPdfBlob(bytes: Uint8Array, fileName: string) {
  const blob = new Blob([bytes], { type: 'application/pdf' });
  downloadBlob(blob, fileName);
}

export function downloadTextAsFile(content: string, fileName: string) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  downloadBlob(blob, fileName);
}

export async function mergePdfDocuments(text1: string, text2: string): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  // Page 1
  const page1 = pdfDoc.addPage([595.28, 841.89]);
  page1.drawText('Merged Document (Part 1)', { x: 50, y: 800, size: 16, font: boldFont, color: rgb(0.1, 0.3, 0.8) });
  const lines1 = text1.split('\n').slice(0, 35);
  let y1 = 760;
  lines1.forEach((l) => {
    page1.drawText(l.slice(0, 80), { x: 50, y: y1, size: 10, font });
    y1 -= 16;
  });

  // Page 2
  const page2 = pdfDoc.addPage([595.28, 841.89]);
  page2.drawText('Merged Document (Part 2)', { x: 50, y: 800, size: 16, font: boldFont, color: rgb(0.1, 0.3, 0.8) });
  const lines2 = text2.split('\n').slice(0, 35);
  let y2 = 760;
  lines2.forEach((l) => {
    page2.drawText(l.slice(0, 80), { x: 50, y: y2, size: 10, font });
    y2 -= 16;
  });

  return await pdfDoc.save();
}

export async function splitPdfDocument(text: string, pages: number[]): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const page = pdfDoc.addPage([595.28, 841.89]);
  page.drawText('Extracted Document Segment', { x: 50, y: 800, size: 16, font: boldFont, color: rgb(0.1, 0.3, 0.8) });
  page.drawText(`Extracted Pages: ${pages.join(', ')}`, { x: 50, y: 775, size: 11, font, color: rgb(0.4, 0.4, 0.5) });

  const lines = text.split('\n').slice(0, 35);
  let y = 740;
  lines.forEach((l) => {
    page.drawText(l.slice(0, 80), { x: 50, y, size: 10, font });
    y -= 16;
  });

  return await pdfDoc.save();
}

export async function compressPdfDocument(text: string): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const page = pdfDoc.addPage([595.28, 841.89]);
  page.drawText('Compressed Document (PDFMind AI)', { x: 50, y: 800, size: 16, font: boldFont });
  const lines = text.split('\n').slice(0, 30);
  let y = 760;
  lines.forEach((l) => {
    page.drawText(l.slice(0, 80), { x: 50, y, size: 10, font });
    y -= 16;
  });

  return await pdfDoc.save({ useObjectStreams: true });
}

export function convertPdfToText(content: string): string {
  return content;
}

export async function exportSummaryToPdf(
  docTitle: string,
  summary: string,
  keyPoints: string[],
  findings: string[],
  conclusion: string
) {
  const doc = new jsPDF();
  
  // Brand Header
  doc.setFillColor(37, 99, 235);
  doc.rect(14, 12, 182, 18, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('PDFMind AI — Executive Document Summary', 20, 24);

  // Metadata
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Document: ${docTitle}`, 14, 38);
  doc.text(`Generated: ${new Date().toLocaleDateString()} | Verification: Ready`, 14, 44);

  doc.setDrawColor(226, 232, 240);
  doc.line(14, 48, 196, 48);

  let cursorY = 56;

  // Executive Summary Section
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text('Executive Summary', 14, cursorY);
  cursorY += 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  const splitSummary = doc.splitTextToSize(summary, 180);
  doc.text(splitSummary, 14, cursorY);
  cursorY += splitSummary.length * 5 + 8;

  // Key Points
  if (keyPoints.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text('Key Highlights & Strategic Points', 14, cursorY);
    cursorY += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(51, 65, 85);
    for (const pt of keyPoints) {
      if (cursorY > 270) {
        doc.addPage();
        cursorY = 20;
      }
      const splitPt = doc.splitTextToSize(`• ${pt}`, 175);
      doc.text(splitPt, 16, cursorY);
      cursorY += splitPt.length * 5 + 3;
    }
    cursorY += 4;
  }

  // Findings
  if (findings.length > 0 && cursorY < 240) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text('Important Findings', 14, cursorY);
    cursorY += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(51, 65, 85);
    for (const f of findings) {
      if (cursorY > 270) {
        doc.addPage();
        cursorY = 20;
      }
      const splitF = doc.splitTextToSize(`→ ${f}`, 175);
      doc.text(splitF, 16, cursorY);
      cursorY += splitF.length * 5 + 3;
    }
    cursorY += 4;
  }

  // Conclusion
  if (conclusion && cursorY < 250) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text('Conclusion & Recommendation', 14, cursorY);
    cursorY += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(71, 85, 105);
    const splitConc = doc.splitTextToSize(conclusion, 180);
    doc.text(splitConc, 14, cursorY);
  }

  // Footer on page
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Confidential & Proprietary — PDFMind AI Document Workspace', 14, 290);

  doc.save(`${docTitle.replace(/\.pdf$/i, '')}_Summary.pdf`);
}
