export interface HelpCategory {
  id: string;
  name: string;
  description: string;
  icon: string;
  articleCount: number;
}

export interface HelpArticle {
  id: string;
  categoryId: string;
  title: string;
  summary: string;
  readTime: string;
  content: string;
}

export const HELP_CATEGORIES: HelpCategory[] = [
  { id: 'getting-started', name: 'Getting Started', description: 'Quick guides to uploading, organizing, and navigating PDFMind AI', icon: 'Sparkles', articleCount: 6 },
  { id: 'documents', name: 'Document Management', description: 'Tagging, filtering, sharing, and batch operations', icon: 'FolderClosed', articleCount: 8 },
  { id: 'ai-chat', name: 'AI Chat & Citations', description: 'Prompting strategies, verifying page references, multi-doc chat', icon: 'MessageSquare', articleCount: 10 },
  { id: 'pdf-tools', name: 'PDF Tools & Conversion', description: 'Merging, splitting, compressing, and format transformations', icon: 'FileStack', articleCount: 9 },
  { id: 'ocr', name: 'OCR & Text Extraction', description: 'Scanned document parsing, language detection, accuracy tuning', icon: 'ScanLine', articleCount: 5 },
  { id: 'translation', name: 'Document Translation', description: 'Multi-lingual support, layout preservation, glossaries', icon: 'Globe', articleCount: 4 },
  { id: 'account', name: 'Account & Security', description: 'Profile management, sessions, 2FA, and data retention', icon: 'ShieldCheck', articleCount: 7 }
];

export const HELP_ARTICLES: HelpArticle[] = [
  {
    id: 'art-1',
    categoryId: 'getting-started',
    title: 'How to upload and index your first PDF document',
    summary: 'Learn how to drag-and-drop documents, monitor OCR indexing, and open the three-column workspace.',
    readTime: '3 min read',
    content: `### Welcome to PDFMind AI
Uploading documents to PDFMind AI is seamless and secure.

1. **Drag and Drop Files**: On the Dashboard or Documents view, drag any PDF, DOCX, PNG, or image file directly into the upload dropzone.
2. **Real-time Pipeline**: Our engine automatically executes:
   - File validation & malware scanning
   - High-fidelity OCR extraction for scanned pages
   - Vector embedding generation for zero-latency semantic search
3. **Open in Workspace**: Once the status indicator displays "Ready", click the document card to launch the interactive viewer and AI assistant.`
  },
  {
    id: 'art-2',
    categoryId: 'ai-chat',
    title: 'Interpreting and clicking Source Citations in AI answers',
    summary: 'Every factual response generated by PDFMind AI includes verifiable page-level source badges.',
    readTime: '2 min read',
    content: `### How Source Grounding Works
PDFMind AI operates strictly on Retrieval-Augmented Generation (RAG) principles. 

- When you ask a question such as *"What were the gross margins in Q3?"*, the AI locates the exact passages in your PDF.
- Answers feature clickable badges such as **Source · Page 1** or **Source · Page 4**.
- Clicking any citation badge automatically scrolls the central document canvas directly to that page and pulses the matching paragraph with a temporary highlight.`
  },
  {
    id: 'art-3',
    categoryId: 'pdf-tools',
    title: 'Compressing and Merging PDFs without losing quality',
    summary: 'Use our client-side WebAssembly and server utilities to optimize file sizes for emailing and archival.',
    readTime: '4 min read',
    content: `### PDF Optimization Utilities
Under the **PDF Tools** workspace:
- **Merge PDF**: Select multiple PDF files, drag to reorder pages, and generate a unified PDF in seconds.
- **Compress PDF**: Choose between Extreme (70% size reduction), Recommended (45% reduction), or High Quality print mode.
- **Convert**: Seamlessly extract tables into editable CSV/Excel or structured Word DOCX formats.`
  },
  {
    id: 'art-4',
    categoryId: 'ocr',
    title: 'Extracting text from low-resolution scans and mobile photos',
    summary: 'Best practices for running OCR on handwritten receipts, signed contracts, and multi-column tables.',
    readTime: '3 min read',
    content: `### Advanced OCR Capabilities
PDFMind AI utilizes multi-modal neural vision models to transcribe complex documents:
- Supports 95+ languages with automatic script detection.
- Retains mathematical symbols, checkboxes, and multi-tier table structures.
- Allows real-time inline text editing before exporting to TXT or searchable PDF.`
  }
];

export const FAQ_ITEMS = [
  {
    q: 'What is PDFMind AI?',
    a: 'PDFMind AI is an all-in-one modern workspace designed to help you read, chat with, summarize, search across, extract text from, translate, and manipulate PDF documents using state-of-the-art artificial intelligence.'
  },
  {
    q: 'Can I chat with a PDF and verify citations?',
    a: 'Yes! PDFMind AI provides interactive conversational intelligence grounded strictly in your document content. Every answer includes clickable page citations (e.g. Source · Page 4) that jump directly to the referenced page.'
  },
  {
    q: 'Can AI read scanned PDFs and mobile photos?',
    a: 'Yes. Our integrated Optical Character Recognition (OCR) engine transcribes scanned documents, photos, and handwritten signatures with 99%+ character accuracy.'
  },
  {
    q: 'What is OCR and how does it work?',
    a: 'OCR stands for Optical Character Recognition. It converts visual pixel data from scanned paper documents or image files into fully searchable, editable digital text.'
  },
  {
    q: 'Can I translate PDFs into other languages?',
    a: 'Yes. The Translation workspace translates entire documents across 50+ languages while preserving structural headings, bullet hierarchies, and numeric data.'
  },
  {
    q: 'How does AI Search work across multiple documents?',
    a: 'AI Search uses semantic vector embeddings. You can ask natural language questions (e.g. "Which document mentions model accuracy?") and receive ranked matches with relevance scores and page jumps.'
  },
  {
    q: 'Can I merge, split, and compress multiple PDFs?',
    a: 'Yes. PDFMind AI includes a comprehensive suite of PDF tools for merging, splitting, compressing, converting to Word/Excel, and extracting raw text.'
  },
  {
    q: 'What file formats are supported?',
    a: 'We support PDF, Microsoft Word (DOCX), PowerPoint (PPTX), Excel (XLSX), and high-resolution images (PNG, JPG, JPEG, WebP).'
  },
  {
    q: 'Are my documents secure and private?',
    a: 'Yes. Your documents are encrypted in transit with TLS 1.3 and at rest with AES-256 GCM encryption. Your data is strictly private and never used to train public foundation models.'
  },
  {
    q: 'Can I download and export processed documents?',
    a: 'Yes! You can download original files, export summaries as PDF or TXT, download translated documents, copy OCR transcripts, and download merged or compressed PDFs with one click.'
  }
];
